### ISSUE TITLE
无法添加到主屏幕

### ISSUE THREAD

**Issue by binggg** [Lizhooh/react-cnode#1]
icon需要是png格式，目前是jpg的

**Comment by Lizhooh** [comment]
@binggg 
查阅相关文档，并没有发现 icons 必须是 png 类型，并且在测试中 jpg 是可以正常添加到主屏幕的。可能是因为一些兼容性问题，导致无法添加到主屏幕。

目前已经更新为 png.

**参考：**

> https://developers.google.cn/web/updates/2014/11/Support-for-installable-web-apps-with-webapp-manifest-in-chrome-38-for-Android

> https://developer.mozilla.org/zh-CN/docs/Web/Manifest
